from pprint import pprint
from dataclasses import asdict

from company.approval.human_approval import STATUS_APPROVED, STATUS_REJECTED
from company.artifacts.scene_asset import SceneAsset
from company.artifacts.script_artifact_parser import ScriptArtifactParser
from company.core.ceo_decision import ACTION_RESEARCH_AGAIN, ACTION_REVISE, ACTION_STOP
from company.core.employee_role import (
    EditorRole,
    ImageRole,
    PublisherRole,
    ResearchRole,
    ReviewerRole,
    VoiceRole,
    WriterRole,
)
from company.core.task import TaskType
from company.core.task_factory import TaskFactory
from company.publishers.youtube_studio_publisher import YouTubeStudioPublisher
from company.reports.quality_feedback import QualityFeedbackParser


class DryRunTextProvider:
    def generate(self, prompt: str) -> str:
        if "調査してください" in prompt:
            return f"research_result: {prompt}"
        if "台本を書いてください" in prompt:
            return f"script_result: {prompt}"
        if "レビューしてください" in prompt:
            return f"review_result: {prompt}"
        return f"text_result: {prompt}"


class DryRunImageGenerator:
    def generate(self, prompt: str) -> str:
        return "dry_run_image.png"


class DryRunVoiceGenerator:
    def generate(self, text: str) -> str:
        return "dry_run_voice.wav"


class DryRunEditor:
    def generate(self, image_paths: list[str], audio_paths: list[str]) -> str:
        return "dry_run_video.mp4"


class VideoEditorAdapter:
    def __init__(self, editor):
        self.editor = editor

    def generate(self, task):
        input_data = getattr(task, "input_data", {}) or {}
        return self.editor.generate(
            image_paths=input_data.get("image_paths", []),
            audio_paths=input_data.get("audio_paths", []),
        )


def create_task(topic: str, instruction: str, extra_input: dict | None = None):
    input_data = {"theme": topic}
    if extra_input:
        input_data.update(extra_input)

    return TaskFactory.create_task(
        task_type=TaskType.GENERAL,
        instruction=instruction,
        input_data=input_data,
    )


def run_role(role, task, role_name: str, execution_order: list[str]):
    execution_order.append(role_name)
    role.prepare(task)
    result = role.execute(task)
    return role.finalize(result)


def create_publish_metadata(topic: str) -> dict:
    return {
        "title": topic,
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
        "status": "draft",
    }


class FullAutoVideoPipeline:
    def __init__(
        self,
        researcher=None,
        writer=None,
        reviewer=None,
        text_provider=None,
        image_generator=None,
        voice_generator=None,
        editor=None,
        publisher=None,
        script_artifact_parser=None,
        scene_video_composer=None,
        quality_retry_limit: int = 0,
        research_retry_limit: int = 0,
        ceo_decision_policy=None,
        stop_on_ceo_stop: bool = False,
        human_approval_gate=None,
        require_human_approval_on_stop: bool = False,
        approval_decision: str | None = None,
        approval_decided_by: str = "human",
        approval_comment: str = "",
    ):
        if quality_retry_limit < 0:
            raise ValueError("quality_retry_limit must be greater than or equal to 0.")
        if research_retry_limit < 0:
            raise ValueError("research_retry_limit must be greater than or equal to 0.")

        text_provider = text_provider or DryRunTextProvider()
        self.researcher = researcher or ResearchRole(provider=text_provider)
        self.writer = writer or WriterRole(provider=text_provider)
        self.reviewer = reviewer or ReviewerRole(provider=text_provider)
        self.image_generator = image_generator or DryRunImageGenerator()
        self.voice_generator = voice_generator or DryRunVoiceGenerator()
        self.editor = editor or DryRunEditor()
        self.publisher = publisher or YouTubeStudioPublisher(dry_run=True)
        self.script_artifact_parser = script_artifact_parser or ScriptArtifactParser()
        self.scene_video_composer = scene_video_composer
        self.quality_feedback_parser = QualityFeedbackParser()
        self.quality_retry_limit = quality_retry_limit
        self.research_retry_limit = research_retry_limit
        self.ceo_decision_policy = ceo_decision_policy
        self.stop_on_ceo_stop = stop_on_ceo_stop
        self.human_approval_gate = human_approval_gate
        self.require_human_approval_on_stop = require_human_approval_on_stop
        self.approval_decision = approval_decision
        self.approval_decided_by = approval_decided_by
        self.approval_comment = approval_comment

    def run(self, topic: str):
        execution_order: list[str] = []

        (
            research_result,
            script_result,
            review_result,
            quality_feedback,
            quality_retry_count,
            quality_retry_history,
            research_retry_count,
            research_retry_history,
            ceo_decision,
            ceo_decision_history,
        ) = self._run_text_decision_loop(topic, execution_order)

        script_artifact = self.script_artifact_parser.parse(script_result)

        if self._should_stop_production(ceo_decision):
            return self._build_stopped_result(
                topic=topic,
                execution_order=execution_order,
                research_result=research_result,
                script_result=script_result,
                script_artifact=script_artifact,
                review_result=review_result,
                quality_feedback=quality_feedback,
                quality_retry_count=quality_retry_count,
                quality_retry_history=quality_retry_history,
                research_retry_count=research_retry_count,
                research_retry_history=research_retry_history,
                ceo_decision=ceo_decision,
                ceo_decision_history=ceo_decision_history,
            )

        scene_assets = self._generate_scene_assets(script_artifact, execution_order)

        if scene_assets:
            image_path = scene_assets[0].image_path
            voice_path = scene_assets[0].voice_path
        elif script_artifact.image_prompts:
            image_prompt_source = script_artifact.image_prompts[0]
            image_path, voice_path = self._generate_single_assets(
                topic=topic,
                image_prompt_source=image_prompt_source,
                script_result=script_result,
                script_artifact=script_artifact,
                review_result=review_result,
                execution_order=execution_order,
            )
        else:
            image_prompt_source = script_result
            image_path, voice_path = self._generate_single_assets(
                topic=topic,
                image_prompt_source=image_prompt_source,
                script_result=script_result,
                script_artifact=script_artifact,
                review_result=review_result,
                execution_order=execution_order,
            )

        scene_video_path = None
        if scene_assets and self.scene_video_composer is not None:
            execution_order.append("Editor")
            scene_video_path = self.scene_video_composer.compose(
                scene_assets,
                output_path="outputs/videos/final_video.mp4",
            )
            video_path = scene_video_path
        else:
            edit_task = create_task(
                topic,
                f"{topic}の動画を編集してください。",
                {
                    "image_paths": [image_path],
                    "audio_paths": [voice_path],
                },
            )
            video_path = run_role(
                EditorRole(editor=VideoEditorAdapter(self.editor)),
                edit_task,
                "Editor",
                execution_order,
            )

        publish_task = create_task(
            topic,
            f"{topic}のYouTube投稿を準備してください。",
            {
                "video_path": video_path,
                "metadata": create_publish_metadata(topic),
            },
        )
        publish_result = run_role(
            PublisherRole(publisher=self.publisher),
            publish_task,
            "Publisher",
            execution_order,
        )

        return {
            "topic": topic,
            "execution_order": execution_order,
            "research_result": research_result,
            "script_result": script_result,
            "script_artifact": script_artifact,
            "scene_assets": scene_assets,
            "review_result": review_result,
            "quality_feedback": quality_feedback,
            "quality_retry_count": quality_retry_count,
            "quality_retry_history": quality_retry_history,
            "research_retry_count": research_retry_count,
            "research_retry_history": research_retry_history,
            "ceo_decision": ceo_decision.to_dict() if ceo_decision is not None else None,
            "ceo_decision_history": ceo_decision_history,
            "image_path": image_path,
            "voice_path": voice_path,
            "scene_video_path": scene_video_path,
            "video_path": video_path,
            "publish_result": publish_result,
            "stopped": False,
            "stop_stage": None,
            "stop_reason": "",
            "production_skipped": False,
            "approval_required": False,
            "approval_request": None,
            "approval_status": "not_required",
            "approval_decision": None,
        }

    def _build_stopped_result(
        self,
        topic: str,
        execution_order: list[str],
        research_result: str,
        script_result: str,
        script_artifact,
        review_result: str,
        quality_feedback: dict,
        quality_retry_count: int,
        quality_retry_history: list[dict],
        research_retry_count: int,
        research_retry_history: list[dict],
        ceo_decision,
        ceo_decision_history: list[dict],
    ) -> dict:
        approval_state = self._build_approval_state(
            topic=topic,
            ceo_decision=ceo_decision,
            quality_feedback=quality_feedback,
            script_result=script_result,
            review_result=review_result,
            quality_retry_count=quality_retry_count,
            quality_retry_history=quality_retry_history,
            research_retry_count=research_retry_count,
            research_retry_history=research_retry_history,
            ceo_decision_history=ceo_decision_history,
        )
        return {
            "topic": topic,
            "execution_order": execution_order,
            "research_result": research_result,
            "script_result": script_result,
            "script_artifact": script_artifact,
            "scene_assets": [],
            "review_result": review_result,
            "quality_feedback": quality_feedback,
            "quality_retry_count": quality_retry_count,
            "quality_retry_history": quality_retry_history,
            "research_retry_count": research_retry_count,
            "research_retry_history": research_retry_history,
            "ceo_decision": ceo_decision.to_dict() if ceo_decision is not None else None,
            "ceo_decision_history": ceo_decision_history,
            "image_path": "",
            "voice_path": "",
            "scene_video_path": None,
            "video_path": "",
            "publish_result": None,
            "stopped": True,
            "stop_stage": self._ceo_stage(ceo_decision) or "review",
            "stop_reason": self._ceo_reason(ceo_decision),
            "production_skipped": True,
            **approval_state,
        }

    def _build_approval_state(
        self,
        *,
        topic: str,
        ceo_decision,
        quality_feedback: dict,
        script_result: str,
        review_result: str,
        quality_retry_count: int,
        quality_retry_history: list[dict],
        research_retry_count: int,
        research_retry_history: list[dict],
        ceo_decision_history: list[dict],
    ) -> dict:
        if not self.require_human_approval_on_stop or self.human_approval_gate is None:
            return {
                "approval_required": False,
                "approval_request": None,
                "approval_status": "not_required",
                "approval_decision": None,
            }

        approval_request = self.human_approval_gate.create_request(
            topic=topic,
            stage=self._ceo_stage(ceo_decision) or "review",
            reason=self._ceo_reason(ceo_decision),
            ceo_action=self._ceo_action(ceo_decision),
            quality_feedback=quality_feedback,
            script_result=script_result,
            review_result=review_result,
            metadata={
                "quality_retry_count": quality_retry_count,
                "research_retry_count": research_retry_count,
                "ceo_decision_history": ceo_decision_history,
                "quality_retry_history": quality_retry_history,
                "research_retry_history": research_retry_history,
            },
        )
        approval_decision = self._resolve_approval_decision(approval_request)
        return {
            "approval_required": True,
            "approval_request": asdict(approval_request),
            "approval_status": approval_request.status,
            "approval_decision": (
                asdict(approval_decision) if approval_decision is not None else None
            ),
        }

    def _resolve_approval_decision(self, approval_request):
        if self.approval_decision == STATUS_APPROVED:
            return self.human_approval_gate.approve(
                approval_request,
                decided_by=self.approval_decided_by,
                comment=self.approval_comment,
            )
        if self.approval_decision == STATUS_REJECTED:
            return self.human_approval_gate.reject(
                approval_request,
                decided_by=self.approval_decided_by,
                comment=self.approval_comment,
            )
        return None

    def _run_text_decision_loop(self, topic: str, execution_order: list[str]):
        research_retry_count = 0
        total_quality_retry_count = 0
        quality_retry_history = []
        research_retry_history = []
        ceo_decision_history = []
        research_input = topic

        while True:
            execution_order.append("Researcher")
            research_result = self.researcher.execute(research_input)

            (
                script_result,
                review_result,
                quality_feedback,
                quality_retry_count,
                cycle_quality_history,
                ceo_decision,
                cycle_ceo_history,
            ) = self._run_quality_retry_loop(
                research_result,
                execution_order,
                research_retry_count=research_retry_count,
            )

            total_quality_retry_count += quality_retry_count
            quality_retry_history.extend(cycle_quality_history)
            ceo_decision_history.extend(cycle_ceo_history)
            research_retry_history.append(
                {
                    "attempt": research_retry_count,
                    "input": research_input,
                    "research_result": research_result,
                    "ceo_action": self._ceo_action(ceo_decision),
                    "ceo_reason": self._ceo_reason(ceo_decision),
                }
            )

            if not self._should_research_retry(ceo_decision, research_retry_count):
                break

            research_retry_count += 1
            research_input = self._build_research_retry_input(
                topic=topic,
                research_result=research_result,
                ceo_decision=ceo_decision,
            )

        return (
            research_result,
            script_result,
            review_result,
            quality_feedback,
            total_quality_retry_count,
            quality_retry_history,
            research_retry_count,
            research_retry_history,
            ceo_decision,
            ceo_decision_history,
        )

    def _run_quality_retry_loop(
        self,
        research_result: str,
        execution_order: list[str],
        research_retry_count: int = 0,
    ):
        execution_order.append("Writer")
        script_result = self.writer.execute(research_result)

        execution_order.append("Reviewer")
        review_result = self.reviewer.execute(script_result)
        quality_feedback = self.quality_feedback_parser.parse(review_result)
        ceo_decision = self._decide_next_action(
            quality_feedback=quality_feedback,
            retry_count=0,
            research_result=research_result,
            research_retry_count=research_retry_count,
        )
        ceo_decision_history = []
        if ceo_decision is not None:
            ceo_decision_history.append(ceo_decision.to_dict())
        history = [
            self._quality_retry_history_entry(
                attempt=0,
                script_result=script_result,
                review_result=review_result,
                quality_feedback=quality_feedback,
            )
        ]

        retry_count = 0
        while (
            self._should_retry(quality_feedback, ceo_decision)
            and retry_count < self.quality_retry_limit
        ):
            retry_count += 1
            revision_input = self._build_revision_input(
                research_result=research_result,
                script_result=script_result,
                quality_feedback=quality_feedback,
            )

            execution_order.append("Writer")
            script_result = self.writer.execute(revision_input)

            execution_order.append("Reviewer")
            review_result = self.reviewer.execute(script_result)
            quality_feedback = self.quality_feedback_parser.parse(review_result)
            ceo_decision = self._decide_next_action(
                quality_feedback=quality_feedback,
                retry_count=retry_count,
                research_result=research_result,
                research_retry_count=research_retry_count,
            )
            if ceo_decision is not None:
                ceo_decision_history.append(ceo_decision.to_dict())
            history.append(
                self._quality_retry_history_entry(
                    attempt=retry_count,
                    script_result=script_result,
                    review_result=review_result,
                    quality_feedback=quality_feedback,
                )
            )

        return (
            script_result,
            review_result,
            asdict(quality_feedback),
            retry_count,
            history,
            ceo_decision,
            ceo_decision_history,
        )

    def _decide_next_action(
        self,
        quality_feedback,
        retry_count: int,
        research_result: str,
        research_retry_count: int,
    ):
        if self.ceo_decision_policy is None:
            return None
        return self.ceo_decision_policy.decide(
            stage="review",
            quality_feedback=quality_feedback,
            retry_count=retry_count,
            retry_limit=self.quality_retry_limit,
            context={
                "research_missing": not str(research_result or "").strip(),
                "research_retry_count": research_retry_count,
                "research_retry_limit": self.research_retry_limit,
            },
        )

    def _should_retry(self, quality_feedback, ceo_decision) -> bool:
        if self.ceo_decision_policy is None:
            return quality_feedback.decision == "修正必要"
        return ceo_decision is not None and ceo_decision.action == ACTION_REVISE

    def _should_research_retry(self, ceo_decision, research_retry_count: int) -> bool:
        if self.ceo_decision_policy is None or ceo_decision is None:
            return False
        return (
            ceo_decision.action == ACTION_RESEARCH_AGAIN
            and research_retry_count < self.research_retry_limit
        )

    def _should_stop_production(self, ceo_decision) -> bool:
        if not self.stop_on_ceo_stop or ceo_decision is None:
            return False
        return self._ceo_action(ceo_decision) == ACTION_STOP

    def _build_research_retry_input(
        self,
        topic: str,
        research_result: str,
        ceo_decision,
    ) -> str:
        return (
            "以下のテーマを再調査してください。\n\n"
            "【テーマ】\n"
            f"{topic}\n\n"
            "【前回の調査結果】\n"
            f"{research_result}\n\n"
            "【再調査理由】\n"
            f"{self._ceo_reason(ceo_decision)}\n\n"
            "不足している情報を補い、\n"
            "今回のテーマから逸脱せず、\n"
            "より具体的で検証しやすい情報を出してください。"
        )

    def _ceo_action(self, ceo_decision) -> str:
        if ceo_decision is None:
            return ""
        if isinstance(ceo_decision, dict):
            return str(ceo_decision.get("action", ""))
        return str(getattr(ceo_decision, "action", ""))

    def _ceo_reason(self, ceo_decision) -> str:
        if ceo_decision is None:
            return ""
        if isinstance(ceo_decision, dict):
            return str(ceo_decision.get("reason", ""))
        return str(getattr(ceo_decision, "reason", ""))

    def _ceo_stage(self, ceo_decision) -> str:
        if ceo_decision is None:
            return ""
        if isinstance(ceo_decision, dict):
            return str(ceo_decision.get("stage", ""))
        return str(getattr(ceo_decision, "stage", ""))

    def _build_revision_input(
        self,
        research_result: str,
        script_result: str,
        quality_feedback,
    ) -> str:
        return (
            "以下の調査結果だけを使って台本を修正してください。\n\n"
            "【調査結果】\n"
            f"{research_result}\n\n"
            "【前回の台本】\n"
            f"{script_result}\n\n"
            "【Reviewerの改善点】\n"
            f"{quality_feedback.improvement_points}\n\n"
            "【Reviewerの評価】\n"
            f"{quality_feedback.evaluation}\n\n"
            "前回の問題を修正し、同じ問題を繰り返さないでください。"
        )

    def _quality_retry_history_entry(
        self,
        attempt: int,
        script_result: str,
        review_result: str,
        quality_feedback,
    ) -> dict:
        return {
            "attempt": attempt,
            "script_result": script_result,
            "review_result": review_result,
            "decision": quality_feedback.decision,
            "score": quality_feedback.score,
            "improvement_points": quality_feedback.improvement_points,
        }

    def _generate_scene_assets(self, script_artifact, execution_order: list[str]):
        scene_assets = []
        if script_artifact.scenes:
            execution_order.extend(["Image", "Voice"])
        for scene in script_artifact.scenes:
            image_path = self.image_generator.generate(scene.image_prompt)
            voice_path = self.voice_generator.generate(scene.narration)
            scene_assets.append(
                SceneAsset(
                    scene_index=scene.index,
                    image_path=image_path,
                    voice_path=voice_path,
                    narration=scene.narration,
                    image_prompt=scene.image_prompt,
                    duration_seconds=scene.duration_seconds,
                )
            )
        return scene_assets

    def _generate_single_assets(
        self,
        topic: str,
        image_prompt_source: str,
        script_result: str,
        script_artifact,
        review_result: str,
        execution_order: list[str],
    ):
        image_task = create_task(
            topic,
            f"{topic}の画像素材を制作してください。",
            {
                "topic": image_prompt_source,
                "script_result": script_result,
                "script_artifact": script_artifact,
                "review_result": review_result,
            },
        )
        voice_task = create_task(
            topic,
            f"{topic}の音声素材を制作してください。",
            {
                "script_result": script_result,
                "script_artifact": script_artifact,
                "review_result": review_result,
            },
        )
        image_path = run_role(
            ImageRole(generator=self.image_generator),
            image_task,
            "Image",
            execution_order,
        )
        voice_path = run_role(
            VoiceRole(generator=self.voice_generator),
            voice_task,
            "Voice",
            execution_order,
        )
        return image_path, voice_path


def run_demo(
    topic: str = "猫の意外な雑学",
    text_provider=None,
    image_generator=None,
    voice_generator=None,
    editor=None,
    publisher=None,
):
    pipeline = FullAutoVideoPipeline(
        text_provider=text_provider,
        image_generator=image_generator,
        voice_generator=voice_generator,
        editor=editor,
        publisher=publisher,
    )
    return pipeline.run(topic)


def main() -> None:
    print("Project SHIRO Version1.2 Full Video Company Dry Run")
    print("Flow: Researcher -> Writer -> Reviewer -> Image -> Voice -> Editor -> Publisher")
    print()
    result = run_demo()
    pprint(result)


if __name__ == "__main__":
    main()
