from pprint import pprint

from company.core.employee_role import (
    EditorRole,
    ImageRole,
    PublisherRole,
    ResearchRole,
    ReviewerRole,
    VoiceRole,
    WriterRole,
)
from company.core.task import TaskType
from company.core.task_factory import TaskFactory
from company.publishers.youtube_studio_publisher import YouTubeStudioPublisher


class DryRunTextProvider:
    def generate(self, prompt: str) -> str:
        if "調査してください" in prompt:
            return f"research_result: {prompt}"
        if "台本を書いてください" in prompt:
            return f"script_result: {prompt}"
        if "レビューしてください" in prompt:
            return f"review_result: {prompt}"
        return f"text_result: {prompt}"


class DryRunImageGenerator:
    def generate(self, prompt: str) -> str:
        return "dry_run_image.png"


class DryRunVoiceGenerator:
    def generate(self, text: str) -> str:
        return "dry_run_voice.wav"


class DryRunEditor:
    def generate(self, image_paths: list[str], audio_paths: list[str]) -> str:
        return "dry_run_video.mp4"


class VideoEditorAdapter:
    def __init__(self, editor):
        self.editor = editor

    def generate(self, task):
        input_data = getattr(task, "input_data", {}) or {}
        return self.editor.generate(
            image_paths=input_data.get("image_paths", []),
            audio_paths=input_data.get("audio_paths", []),
        )


def create_task(topic: str, instruction: str, extra_input: dict | None = None):
    input_data = {"theme": topic}
    if extra_input:
        input_data.update(extra_input)

    return TaskFactory.create_task(
        task_type=TaskType.GENERAL,
        instruction=instruction,
        input_data=input_data,
    )


def run_role(role, task, role_name: str, execution_order: list[str]):
    execution_order.append(role_name)
    role.prepare(task)
    result = role.execute(task)
    return role.finalize(result)


def create_publish_metadata(topic: str) -> dict:
    return {
        "title": topic,
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
        "status": "draft",
    }


def run_demo(
    topic: str = "猫の意外な雑学",
    text_provider=None,
    image_generator=None,
    voice_generator=None,
    editor=None,
    publisher=None,
):
    text_provider = text_provider or DryRunTextProvider()
    image_generator = image_generator or DryRunImageGenerator()
    voice_generator = voice_generator or DryRunVoiceGenerator()
    editor = editor or DryRunEditor()
    publisher = publisher or YouTubeStudioPublisher(dry_run=True)
    execution_order: list[str] = []

    research_task = create_task(topic, f"{topic}について調査してください。")
    research_result = run_role(
        ResearchRole(provider=text_provider),
        research_task,
        "Researcher",
        execution_order,
    )

    script_task = create_task(
        topic,
        f"{topic}について台本を書いてください。",
        {"research_result": research_result},
    )
    script_result = run_role(
        WriterRole(provider=text_provider),
        script_task,
        "Writer",
        execution_order,
    )

    review_task = create_task(
        topic,
        f"{topic}の台本をレビューしてください。",
        {
            "research_result": research_result,
            "script_result": script_result,
        },
    )
    review_result = run_role(
        ReviewerRole(provider=text_provider),
        review_task,
        "Reviewer",
        execution_order,
    )

    media_task = create_task(
        topic,
        f"{topic}の動画素材を制作してください。",
        {
            "script_result": script_result,
            "review_result": review_result,
        },
    )
    image_path = run_role(
        ImageRole(generator=image_generator),
        media_task,
        "Image",
        execution_order,
    )
    voice_path = run_role(
        VoiceRole(generator=voice_generator),
        media_task,
        "Voice",
        execution_order,
    )

    edit_task = create_task(
        topic,
        f"{topic}の動画を編集してください。",
        {
            "image_paths": [image_path],
            "audio_paths": [voice_path],
        },
    )
    video_path = run_role(
        EditorRole(editor=VideoEditorAdapter(editor)),
        edit_task,
        "Editor",
        execution_order,
    )

    publish_task = create_task(
        topic,
        f"{topic}のYouTube投稿を準備してください。",
        {
            "video_path": video_path,
            "metadata": create_publish_metadata(topic),
        },
    )
    publish_result = run_role(
        PublisherRole(publisher=publisher),
        publish_task,
        "Publisher",
        execution_order,
    )

    return {
        "topic": topic,
        "execution_order": execution_order,
        "research_result": research_result,
        "script_result": script_result,
        "review_result": review_result,
        "image_path": image_path,
        "voice_path": voice_path,
        "video_path": video_path,
        "publish_result": publish_result,
    }


def main() -> None:
    print("Project SHIRO Version1.2 Full Video Company Dry Run")
    print("Flow: Researcher -> Writer -> Reviewer -> Image -> Voice -> Editor -> Publisher")
    print()
    result = run_demo()
    pprint(result)


if __name__ == "__main__":
    main()
