from pprint import pprint

from company.automation.browser import FakeBrowserController
from company.publishers.youtube_studio_publisher import YouTubeStudioPublisher


def run_youtube_upload_flow_demo():
    video_path = "outputs/videos/final_video.mp4"
    metadata = {
        "title": "猫の意外な雑学",
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
    }

    browser = FakeBrowserController()
    publisher = YouTubeStudioPublisher(browser=browser)

    publish_result = publisher.publish(video_path, metadata)

    return {
        "publish_result": publish_result,
        "browser_actions": browser.actions,
    }


if __name__ == "__main__":
    result = run_youtube_upload_flow_demo()

    print("Publish result:")
    pprint(result["publish_result"])
    print("\nBrowser actions:")
    pprint(result["browser_actions"])

