from company.automation.browser import FakeBrowserController


def run_youtube_draft_save_check(
    browser,
    video_path: str,
    metadata: dict,
    url: str = "https://studio.youtube.com",
) -> dict:

    if not video_path:
        raise ValueError("video_path is required")

    if not metadata.get("title"):
        raise ValueError("metadata title is required")

    browser.open(url)

    browser.click(
        "ytcp-button#create-icon"
    )

    browser.click(
        "tp-yt-paper-item#text-item-0"
    )

    browser.upload(
        "input[type=file]",
        video_path,
    )

    browser.fill(
        "input[name=title]",
        metadata["title"],
    )

    browser.fill(
        "textarea[name=description]",
        metadata.get("description", ""),
    )

    # next buttons
    browser.click(
        "ytcp-button#next-button"
    )

    browser.click(
        "ytcp-button#next-button"
    )

    browser.click(
        "ytcp-button#next-button"
    )

    # save draft only
    browser.click(
        "ytcp-button#done-button"
    )

    return {
        "status": "draft_saved",
        "video_path": video_path,
        "title": metadata["title"],
    }


if __name__ == "__main__":

    browser = FakeBrowserController()

    result = run_youtube_draft_save_check(
        browser,
        "outputs/videos/final_video.mp4",
        {
            "title": "猫の意外な雑学",
            "description": "Generated by Project SHIRO",
        },
    )

    print(result)
    print(browser.actions)