from company.automation.browser import FakeBrowserController


def run_youtube_metadata_fill_check(
    browser,
    video_path: str,
    metadata: dict,
    url: str = "https://studio.youtube.com",
) -> dict:
    if not video_path:
        raise ValueError("video_path is required")

    if not metadata.get("title"):
        raise ValueError("metadata title is required")

    title = metadata["title"]
    description = metadata.get("description", "")
    tags = metadata.get("tags", [])

    browser.open(url)
    browser.click("ytcp-button#create-icon")
    browser.click("tp-yt-paper-item#text-item-0")
    browser.upload("input[type=file]", video_path)
    browser.fill("input[name=title]", title)
    browser.fill("textarea[name=description]", description)

    if tags:
        browser.fill("input[name=tags]", ",".join(tags))

    return {
        "status": "metadata_filled",
        "video_path": video_path,
        "title": title,
        "description": description,
        "tags": tags,
        "url": url,
    }


if __name__ == "__main__":
    browser = FakeBrowserController()

    result = run_youtube_metadata_fill_check(
        browser,
        "outputs/videos/final_video.mp4",
        {
            "title": "猫の意外な雑学",
            "description": "Generated by Project SHIRO",
            "tags": ["AI", "雑学", "Shorts"],
        },
    )

    print(result)
    print(browser.actions)