from company.automation.browser import FakeBrowserController
from company.core.ai_company import AICompany


class FullAutoVideoPipelineRunner:
    def __init__(
        self,
        image_generator=None,
        voice_generator=None,
        editor=None,
        browser=None,
    ):
        self.image_generator = image_generator or FakeImageGenerator()
        self.voice_generator = voice_generator or FakeVoiceGenerator()
        self.editor = editor or FakeEditor()
        self.browser = browser or FakeBrowserController()

    def run(self, topic: str) -> dict:
        if not topic:
            raise ValueError("topic is required")

        research_result = f"Research result for: {topic}"
        script_result = f"Script draft for: {topic}"
        review_result = f"Review result: approved for {topic}"

        image_path = self.image_generator.generate(script_result)
        voice_path = self.voice_generator.generate(script_result)
        video_path = self.editor.generate(
            [image_path],
            [voice_path],
        )

        metadata = {
            "title": topic,
            "description": "Generated by Project SHIRO",
            "tags": ["AI", "雑学", "Shorts"],
        }

        self.browser.open("https://studio.youtube.com")
        self.browser.click("ytcp-button#create-icon")
        self.browser.click("tp-yt-paper-item#text-item-0")
        self.browser.upload("input[type=file]", video_path)
        self.browser.fill("input[name=title]", metadata["title"])
        self.browser.fill("textarea[name=description]", metadata["description"])
        self.browser.fill("input[name=tags]", ",".join(metadata["tags"]))

        self.browser.click("ytcp-button#next-button")
        self.browser.click("ytcp-button#next-button")
        self.browser.click("ytcp-button#next-button")
        self.browser.click("ytcp-button#done-button")

        return {
            "status": "draft_saved",
            "topic": topic,
            "research_result": research_result,
            "script_result": script_result,
            "review_result": review_result,
            "image_path": image_path,
            "voice_path": voice_path,
            "video_path": video_path,
            "metadata": metadata,
            "browser_actions": self.browser.actions,
        }


class FakeImageGenerator:
    def generate(self, prompt: str) -> str:
        return "outputs/images/fake_image.png"


class FakeVoiceGenerator:
    def generate(self, text: str) -> str:
        return "outputs/voices/fake_voice.wav"


class FakeEditor:
    def generate(self, image_paths, audio_paths) -> str:
        return "outputs/videos/final_video.mp4"


def build_company() -> AICompany:
    return AICompany(
        runner=FullAutoVideoPipelineRunner()
    )


if __name__ == "__main__":
    company = build_company()

    result = company.run(
        "猫の意外な雑学"
    )

    print(result)