from pprint import pprint

from company.publishers.youtube_studio_publisher import YouTubeStudioPublisher


def run_manual_upload(
    video_path: str,
    metadata: dict,
    browser,
    output_dir: str = "outputs/publish",
) -> dict:
    publisher = YouTubeStudioPublisher(
        dry_run=True,
        browser=browser,
        output_dir=output_dir,
    )
    publish_result = publisher.publish(video_path, metadata)

    return {
        "publish_result": publish_result,
        "browser_actions": getattr(browser, "actions", []),
    }


def main() -> dict:
    from playwright.sync_api import sync_playwright

    from company.automation.playwright_browser import PlaywrightBrowserController

    video_path = "outputs/videos/final_video.mp4"
    metadata = {
        "title": "猫の意外な雑学",
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
    }

    with sync_playwright() as playwright:
        browser_instance = playwright.chromium.launch(headless=False)
        page = browser_instance.new_page()
        browser = PlaywrightBrowserController(page=page)
        result = run_manual_upload(video_path, metadata, browser)

        print("Publish result:")
        pprint(result["publish_result"])
        print("\nManual browser flow completed in dry-run mode.")
        return result


if __name__ == "__main__":
    main()

