from pprint import pprint
from dataclasses import asdict

from company.artifacts.scene_asset import SceneAsset
from company.artifacts.script_artifact_parser import ScriptArtifactParser
from company.core.employee_role import (
    EditorRole,
    ImageRole,
    PublisherRole,
    ResearchRole,
    ReviewerRole,
    VoiceRole,
    WriterRole,
)
from company.core.task import TaskType
from company.core.task_factory import TaskFactory
from company.publishers.youtube_studio_publisher import YouTubeStudioPublisher
from company.reports.quality_feedback import QualityFeedbackParser


class DryRunTextProvider:
    def generate(self, prompt: str) -> str:
        if "調査してください" in prompt:
            return f"research_result: {prompt}"
        if "台本を書いてください" in prompt:
            return f"script_result: {prompt}"
        if "レビューしてください" in prompt:
            return f"review_result: {prompt}"
        return f"text_result: {prompt}"


class DryRunImageGenerator:
    def generate(self, prompt: str) -> str:
        return "dry_run_image.png"


class DryRunVoiceGenerator:
    def generate(self, text: str) -> str:
        return "dry_run_voice.wav"


class DryRunEditor:
    def generate(self, image_paths: list[str], audio_paths: list[str]) -> str:
        return "dry_run_video.mp4"


class VideoEditorAdapter:
    def __init__(self, editor):
        self.editor = editor

    def generate(self, task):
        input_data = getattr(task, "input_data", {}) or {}
        return self.editor.generate(
            image_paths=input_data.get("image_paths", []),
            audio_paths=input_data.get("audio_paths", []),
        )


def create_task(topic: str, instruction: str, extra_input: dict | None = None):
    input_data = {"theme": topic}
    if extra_input:
        input_data.update(extra_input)

    return TaskFactory.create_task(
        task_type=TaskType.GENERAL,
        instruction=instruction,
        input_data=input_data,
    )


def run_role(role, task, role_name: str, execution_order: list[str]):
    execution_order.append(role_name)
    role.prepare(task)
    result = role.execute(task)
    return role.finalize(result)


def create_publish_metadata(topic: str) -> dict:
    return {
        "title": topic,
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
        "status": "draft",
    }


class FullAutoVideoPipeline:
    def __init__(
        self,
        researcher=None,
        writer=None,
        reviewer=None,
        text_provider=None,
        image_generator=None,
        voice_generator=None,
        editor=None,
        publisher=None,
        script_artifact_parser=None,
        scene_video_composer=None,
        quality_retry_limit: int = 0,
    ):
        if quality_retry_limit < 0:
            raise ValueError("quality_retry_limit must be greater than or equal to 0.")

        text_provider = text_provider or DryRunTextProvider()
        self.researcher = researcher or ResearchRole(provider=text_provider)
        self.writer = writer or WriterRole(provider=text_provider)
        self.reviewer = reviewer or ReviewerRole(provider=text_provider)
        self.image_generator = image_generator or DryRunImageGenerator()
        self.voice_generator = voice_generator or DryRunVoiceGenerator()
        self.editor = editor or DryRunEditor()
        self.publisher = publisher or YouTubeStudioPublisher(dry_run=True)
        self.script_artifact_parser = script_artifact_parser or ScriptArtifactParser()
        self.scene_video_composer = scene_video_composer
        self.quality_feedback_parser = QualityFeedbackParser()
        self.quality_retry_limit = quality_retry_limit

    def run(self, topic: str):
        execution_order: list[str] = []

        execution_order.append("Researcher")
        research_result = self.researcher.execute(topic)

        (
            script_result,
            review_result,
            quality_feedback,
            quality_retry_count,
            quality_retry_history,
        ) = self._run_quality_retry_loop(research_result, execution_order)

        script_artifact = self.script_artifact_parser.parse(script_result)

        scene_assets = self._generate_scene_assets(script_artifact, execution_order)

        if scene_assets:
            image_path = scene_assets[0].image_path
            voice_path = scene_assets[0].voice_path
        elif script_artifact.image_prompts:
            image_prompt_source = script_artifact.image_prompts[0]
            image_path, voice_path = self._generate_single_assets(
                topic=topic,
                image_prompt_source=image_prompt_source,
                script_result=script_result,
                script_artifact=script_artifact,
                review_result=review_result,
                execution_order=execution_order,
            )
        else:
            image_prompt_source = script_result
            image_path, voice_path = self._generate_single_assets(
                topic=topic,
                image_prompt_source=image_prompt_source,
                script_result=script_result,
                script_artifact=script_artifact,
                review_result=review_result,
                execution_order=execution_order,
            )

        scene_video_path = None
        if scene_assets and self.scene_video_composer is not None:
            execution_order.append("Editor")
            scene_video_path = self.scene_video_composer.compose(
                scene_assets,
                output_path="outputs/videos/final_video.mp4",
            )
            video_path = scene_video_path
        else:
            edit_task = create_task(
                topic,
                f"{topic}の動画を編集してください。",
                {
                    "image_paths": [image_path],
                    "audio_paths": [voice_path],
                },
            )
            video_path = run_role(
                EditorRole(editor=VideoEditorAdapter(self.editor)),
                edit_task,
                "Editor",
                execution_order,
            )

        publish_task = create_task(
            topic,
            f"{topic}のYouTube投稿を準備してください。",
            {
                "video_path": video_path,
                "metadata": create_publish_metadata(topic),
            },
        )
        publish_result = run_role(
            PublisherRole(publisher=self.publisher),
            publish_task,
            "Publisher",
            execution_order,
        )

        return {
            "topic": topic,
            "execution_order": execution_order,
            "research_result": research_result,
            "script_result": script_result,
            "script_artifact": script_artifact,
            "scene_assets": scene_assets,
            "review_result": review_result,
            "quality_feedback": quality_feedback,
            "quality_retry_count": quality_retry_count,
            "quality_retry_history": quality_retry_history,
            "image_path": image_path,
            "voice_path": voice_path,
            "scene_video_path": scene_video_path,
            "video_path": video_path,
            "publish_result": publish_result,
        }

    def _run_quality_retry_loop(
        self,
        research_result: str,
        execution_order: list[str],
    ):
        execution_order.append("Writer")
        script_result = self.writer.execute(research_result)

        execution_order.append("Reviewer")
        review_result = self.reviewer.execute(script_result)
        quality_feedback = self.quality_feedback_parser.parse(review_result)
        history = [
            self._quality_retry_history_entry(
                attempt=0,
                script_result=script_result,
                review_result=review_result,
                quality_feedback=quality_feedback,
            )
        ]

        retry_count = 0
        while (
            quality_feedback.decision == "修正必要"
            and retry_count < self.quality_retry_limit
        ):
            retry_count += 1
            revision_input = self._build_revision_input(
                research_result=research_result,
                script_result=script_result,
                quality_feedback=quality_feedback,
            )

            execution_order.append("Writer")
            script_result = self.writer.execute(revision_input)

            execution_order.append("Reviewer")
            review_result = self.reviewer.execute(script_result)
            quality_feedback = self.quality_feedback_parser.parse(review_result)
            history.append(
                self._quality_retry_history_entry(
                    attempt=retry_count,
                    script_result=script_result,
                    review_result=review_result,
                    quality_feedback=quality_feedback,
                )
            )

        return (
            script_result,
            review_result,
            asdict(quality_feedback),
            retry_count,
            history,
        )

    def _build_revision_input(
        self,
        research_result: str,
        script_result: str,
        quality_feedback,
    ) -> str:
        return (
            "以下の調査結果だけを使って台本を修正してください。\n\n"
            "【調査結果】\n"
            f"{research_result}\n\n"
            "【前回の台本】\n"
            f"{script_result}\n\n"
            "【Reviewerの改善点】\n"
            f"{quality_feedback.improvement_points}\n\n"
            "【Reviewerの評価】\n"
            f"{quality_feedback.evaluation}\n\n"
            "前回の問題を修正し、同じ問題を繰り返さないでください。"
        )

    def _quality_retry_history_entry(
        self,
        attempt: int,
        script_result: str,
        review_result: str,
        quality_feedback,
    ) -> dict:
        return {
            "attempt": attempt,
            "script_result": script_result,
            "review_result": review_result,
            "decision": quality_feedback.decision,
            "score": quality_feedback.score,
            "improvement_points": quality_feedback.improvement_points,
        }

    def _generate_scene_assets(self, script_artifact, execution_order: list[str]):
        scene_assets = []
        if script_artifact.scenes:
            execution_order.extend(["Image", "Voice"])
        for scene in script_artifact.scenes:
            image_path = self.image_generator.generate(scene.image_prompt)
            voice_path = self.voice_generator.generate(scene.narration)
            scene_assets.append(
                SceneAsset(
                    scene_index=scene.index,
                    image_path=image_path,
                    voice_path=voice_path,
                    narration=scene.narration,
                    image_prompt=scene.image_prompt,
                    duration_seconds=scene.duration_seconds,
                )
            )
        return scene_assets

    def _generate_single_assets(
        self,
        topic: str,
        image_prompt_source: str,
        script_result: str,
        script_artifact,
        review_result: str,
        execution_order: list[str],
    ):
        image_task = create_task(
            topic,
            f"{topic}の画像素材を制作してください。",
            {
                "topic": image_prompt_source,
                "script_result": script_result,
                "script_artifact": script_artifact,
                "review_result": review_result,
            },
        )
        voice_task = create_task(
            topic,
            f"{topic}の音声素材を制作してください。",
            {
                "script_result": script_result,
                "script_artifact": script_artifact,
                "review_result": review_result,
            },
        )
        image_path = run_role(
            ImageRole(generator=self.image_generator),
            image_task,
            "Image",
            execution_order,
        )
        voice_path = run_role(
            VoiceRole(generator=self.voice_generator),
            voice_task,
            "Voice",
            execution_order,
        )
        return image_path, voice_path


def run_demo(
    topic: str = "猫の意外な雑学",
    text_provider=None,
    image_generator=None,
    voice_generator=None,
    editor=None,
    publisher=None,
):
    pipeline = FullAutoVideoPipeline(
        text_provider=text_provider,
        image_generator=image_generator,
        voice_generator=voice_generator,
        editor=editor,
        publisher=publisher,
    )
    return pipeline.run(topic)


def main() -> None:
    print("Project SHIRO Version1.2 Full Video Company Dry Run")
    print("Flow: Researcher -> Writer -> Reviewer -> Image -> Voice -> Editor -> Publisher")
    print()
    result = run_demo()
    pprint(result)


if __name__ == "__main__":
    main()
