from company.core.employee import Employee
from company.core.employee_role import PublisherRole
from company.core.task import TaskType
from company.core.task_factory import TaskFactory


class FakeBrain:
    def ask(self, role, prompt):
        return f"{role}: {prompt}"


class FakeTaskExecutor:
    def __init__(self):
        self.executed_tasks = []

    def execute(self, task):
        self.executed_tasks.append(task)
        task.complete({"result": "executor result"})
        return task


class FakeGeneratePublisher:
    def __init__(self, response=None):
        self.response = response or {"status": "generated"}
        self.tasks = []

    def generate(self, task):
        self.tasks.append(task)
        return self.response


class FakePublishPublisher:
    def __init__(self, response=None):
        self.response = response or {"status": "published"}
        self.tasks = []

    def publish(self, task):
        self.tasks.append(task)
        return self.response


def _task(input_data=None, instruction="猫の意外な雑学を投稿してください。"):
    return TaskFactory.create_task(
        task_type=TaskType.GENERAL,
        instruction=instruction,
        input_data={"theme": "猫の意外な雑学"} if input_data is None else input_data,
    )


def test_publisher_role_name_is_publisher():
    assert PublisherRole().name == "Publisher"


def test_publisher_role_without_publisher_returns_metadata_dict():
    role = PublisherRole()
    task = _task()

    role.prepare(task)
    result = role.execute(task)

    assert result == {
        "title": "猫の意外な雑学",
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
        "status": "draft",
    }


def test_publisher_role_metadata_contains_required_keys():
    role = PublisherRole()
    task = _task()

    role.prepare(task)
    result = role.execute(task)

    assert "title" in result
    assert "description" in result
    assert "tags" in result
    assert "status" in result


def test_publisher_role_uses_topic_from_input_data():
    role = PublisherRole()
    task = _task(input_data={"topic": "犬の行動心理"})

    role.prepare(task)
    result = role.execute(task)

    assert result["title"] == "犬の行動心理"


def test_publisher_role_with_generate_publisher_calls_generate():
    publisher = FakeGeneratePublisher(response={"status": "metadata generated"})
    role = PublisherRole(publisher=publisher)
    task = _task()

    role.prepare(task)
    result = role.execute(task)

    assert result == {"status": "metadata generated"}
    assert publisher.tasks == [task]


def test_publisher_role_with_publish_publisher_calls_publish():
    publisher = FakePublishPublisher(response={"status": "draft published"})
    role = PublisherRole(publisher=publisher)
    task = _task()

    role.prepare(task)
    result = role.execute(task)

    assert result == {"status": "draft published"}
    assert publisher.tasks == [task]


def test_publisher_role_finalize_returns_result():
    role = PublisherRole()
    result = {"status": "draft"}

    assert role.finalize(result) is result


def test_publisher_role_integrates_with_employee_execute_task():
    publisher = FakeGeneratePublisher(response={"status": "employee generated"})
    role = PublisherRole(publisher=publisher)
    executor = FakeTaskExecutor()
    employee = Employee(
        name="PublisherEmployee",
        role=role,
        brain=FakeBrain(),
        task_executor=executor,
    )
    task = _task()

    result = employee.execute_task(task)

    assert result == {"status": "employee generated"}
    assert publisher.tasks == [task]
    assert executor.executed_tasks == []
