from main_v13_youtube_upload_flow_demo import run_youtube_upload_flow_demo


def test_youtube_upload_flow_demo_returns_dry_run_status():
    result = run_youtube_upload_flow_demo()

    assert result["publish_result"]["status"] == "dry_run"


def test_youtube_upload_flow_demo_records_open_action():
    result = run_youtube_upload_flow_demo()

    assert ("open", "https://studio.youtube.com") in result["browser_actions"]


def test_youtube_upload_flow_demo_records_upload_action():
    result = run_youtube_upload_flow_demo()

    assert (
        "upload",
        "input[type=file]",
        "outputs/videos/final_video.mp4",
    ) in result["browser_actions"]


def test_youtube_upload_flow_demo_records_title_fill_action():
    result = run_youtube_upload_flow_demo()

    assert (
        "fill",
        "input[name=title]",
        "猫の意外な雑学",
    ) in result["browser_actions"]


def test_youtube_upload_flow_demo_records_description_fill_action():
    result = run_youtube_upload_flow_demo()

    assert (
        "fill",
        "textarea[name=description]",
        "Generated by Project SHIRO",
    ) in result["browser_actions"]


def test_youtube_upload_flow_demo_records_click_action():
    result = run_youtube_upload_flow_demo()

    assert (
        "click",
        "button[data-test-id=draft-save]",
    ) in result["browser_actions"]


def test_youtube_upload_flow_demo_records_actions_in_order():
    result = run_youtube_upload_flow_demo()

    assert result["browser_actions"] == [
        ("open", "https://studio.youtube.com"),
        ("upload", "input[type=file]", "outputs/videos/final_video.mp4"),
        ("fill", "input[name=title]", "猫の意外な雑学"),
        (
            "fill",
            "textarea[name=description]",
            "Generated by Project SHIRO",
        ),
        ("fill", "input[name=tags]", "AI, 雑学, Shorts"),
        ("click", "button[data-test-id=draft-save]"),
    ]
