from company.automation.browser import FakeBrowserController
from main_v13_youtube_playwright_manual import run_manual_upload


def _metadata():
    return {
        "title": "猫の意外な雑学",
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
    }


def test_run_manual_upload_returns_dry_run_result(tmp_path):
    browser = FakeBrowserController()

    result = run_manual_upload(
        "outputs/videos/final_video.mp4",
        _metadata(),
        browser,
        output_dir=str(tmp_path),
    )

    assert result["publish_result"]["status"] == "dry_run"


def test_run_manual_upload_records_browser_actions(tmp_path):
    browser = FakeBrowserController()

    result = run_manual_upload(
        "outputs/videos/final_video.mp4",
        _metadata(),
        browser,
        output_dir=str(tmp_path),
    )

    assert result["browser_actions"] == [
        ("open", "https://studio.youtube.com"),
        ("upload", "input[type=file]", "outputs/videos/final_video.mp4"),
        ("fill", "input[name=title]", "猫の意外な雑学"),
        (
            "fill",
            "textarea[name=description]",
            "Generated by Project SHIRO",
        ),
        ("fill", "input[name=tags]", "AI, 雑学, Shorts"),
        ("click", "button[data-test-id=draft-save]"),
    ]


def test_run_manual_upload_reflects_video_path(tmp_path):
    browser = FakeBrowserController()

    result = run_manual_upload(
        "outputs/videos/custom_video.mp4",
        _metadata(),
        browser,
        output_dir=str(tmp_path),
    )

    assert result["publish_result"]["video_path"] == "outputs/videos/custom_video.mp4"
    assert (
        "upload",
        "input[type=file]",
        "outputs/videos/custom_video.mp4",
    ) in result["browser_actions"]


def test_run_manual_upload_reflects_title(tmp_path):
    browser = FakeBrowserController()
    metadata = _metadata()
    metadata["title"] = "犬の行動心理"

    result = run_manual_upload(
        "outputs/videos/final_video.mp4",
        metadata,
        browser,
        output_dir=str(tmp_path),
    )

    assert result["publish_result"]["title"] == "犬の行動心理"
    assert ("fill", "input[name=title]", "犬の行動心理") in result[
        "browser_actions"
    ]


def test_run_manual_upload_does_not_require_playwright_for_tests(tmp_path):
    browser = FakeBrowserController()

    result = run_manual_upload(
        "outputs/videos/final_video.mp4",
        _metadata(),
        browser,
        output_dir=str(tmp_path),
    )

    assert result["browser_actions"][0] == ("open", "https://studio.youtube.com")
