import json

import pytest

from company.automation.browser import FakeBrowserController
from company.core.task import TaskType
from company.core.task_factory import TaskFactory
from company.publishers.youtube_studio_publisher import YouTubeStudioPublisher


def _metadata():
    return {
        "title": "猫の意外な雑学",
        "description": "Generated by Project SHIRO",
        "tags": ["AI", "雑学", "Shorts"],
    }


def test_youtube_studio_publisher_dry_run_publish_returns_dict(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))

    result = publisher.publish("final_video.mp4", _metadata())

    assert isinstance(result, dict)


def test_youtube_studio_publisher_dry_run_status_is_dry_run(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))

    result = publisher.publish("final_video.mp4", _metadata())

    assert result["status"] == "dry_run"


def test_youtube_studio_publisher_dry_run_result_contains_metadata(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))

    result = publisher.publish("final_video.mp4", _metadata())

    assert result["video_path"] == "final_video.mp4"
    assert result["title"] == "猫の意外な雑学"
    assert result["description"] == "Generated by Project SHIRO"
    assert result["tags"] == ["AI", "雑学", "Shorts"]


def test_youtube_studio_publisher_empty_video_path_raises_value_error(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))

    with pytest.raises(ValueError, match="video_path must not be empty"):
        publisher.publish("", _metadata())


def test_youtube_studio_publisher_missing_title_raises_value_error(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))
    metadata = {
        "description": "Generated by Project SHIRO",
        "tags": ["AI"],
    }

    with pytest.raises(ValueError, match="metadata title is required"):
        publisher.publish("final_video.mp4", metadata)


def test_youtube_studio_publisher_dry_run_false_raises_not_implemented_error(
    tmp_path,
):
    publisher = YouTubeStudioPublisher(dry_run=False, output_dir=str(tmp_path))

    with pytest.raises(NotImplementedError, match="real upload is not implemented"):
        publisher.publish("final_video.mp4", _metadata())


def test_youtube_studio_publisher_saves_dry_run_json(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))

    result = publisher.publish("final_video.mp4", _metadata())
    saved_files = list(tmp_path.glob("youtube_dry_run_*.json"))

    assert len(saved_files) == 1
    assert json.loads(saved_files[0].read_text(encoding="utf-8")) == result


def test_youtube_studio_publisher_generate_accepts_task_payload(tmp_path):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))
    task = TaskFactory.create_task(
        task_type=TaskType.GENERAL,
        instruction="YouTube投稿準備をしてください。",
        input_data={
            "video_path": "final_video.mp4",
            "metadata": _metadata(),
        },
    )

    result = publisher.generate(task)

    assert result["status"] == "dry_run"
    assert result["video_path"] == "final_video.mp4"
    assert result["title"] == "猫の意外な雑学"


def test_youtube_studio_publisher_without_browser_keeps_dry_run_behavior(
    tmp_path,
):
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path))

    result = publisher.publish("final_video.mp4", _metadata())

    assert result["status"] == "dry_run"
    assert result["video_path"] == "final_video.mp4"
    assert result["title"] == "猫の意外な雑学"


def test_youtube_studio_publisher_records_browser_actions_in_order(tmp_path):
    browser = FakeBrowserController()
    publisher = YouTubeStudioPublisher(
        upload_url="https://studio.youtube.com",
        output_dir=str(tmp_path),
        browser=browser,
    )

    publisher.publish("final_video.mp4", _metadata())

    assert browser.actions == [
        ("open", "https://studio.youtube.com"),
        ("upload", "input[type=file]", "final_video.mp4"),
        ("fill", "input[name=title]", "猫の意外な雑学"),
        (
            "fill",
            "textarea[name=description]",
            "Generated by Project SHIRO",
        ),
        ("fill", "input[name=tags]", "AI, 雑学, Shorts"),
        ("click", "button[data-test-id=draft-save]"),
    ]


def test_youtube_studio_publisher_browser_records_empty_description(tmp_path):
    browser = FakeBrowserController()
    publisher = YouTubeStudioPublisher(output_dir=str(tmp_path), browser=browser)

    publisher.publish(
        "final_video.mp4",
        {
            "title": "猫の意外な雑学",
        },
    )

    assert (
        "fill",
        "textarea[name=description]",
        "",
    ) in browser.actions
